### ISSUE TITLE
大神有没有尝试过采用分片上传的功能？个人尝试后可以上传成功，但是文件夹不显示文件。

### ISSUE THREAD

**Issue by canwushuang** [orzogc/fake115uploader#1]
想把本地化的上传记录改为用“分片上传”接口的upload_id。经过尝试，可以上传成功，但是不显示文件。大神有没有尝试过分片上传的思路？
如果实现，也就是可以根据这个upload_id进行多线程且分布式上传。

**Comment by orzogc** [comment]
断点续传模式用的就是阿里OSS的[分片上传](https://help.aliyun.com/document_detail/88604.html)接口，115客户端也是用这个接口上传文件。
虽然我没尝试过， [UploadPart](https://pkg.go.dev/github.com/aliyun/aliyun-oss-go-sdk@v2.1.4+incompatible/oss?tab=doc#Bucket.UploadPart) 可能可以实现多线程上传，你可以使用不同的`partNumber`同时上传试试。多线程上传的速度应该比单线程的快不了多少吧。
至于你说的“分片上传”是指OSS的[断点续传](https://help.aliyun.com/document_detail/88603.html)接口吗？这个我也尝试过，结果是不行的，115那边应该没有允许这种上传方式。

**Comment by canwushuang** [comment]
恩，就是分片上传。我这边上传完毕没有成功回调，之前callback加在了请求头里面，看了OSS python sdk的一些例子，需要构建新字典。不像普通上传put object from file这个封装，可以加在header里。和go的sdk有些不一样。

另外，这里提一下给需要python实现的朋友，go sdk不分stsauth（临时token）的，直接auth调用，而python这边需Oss2.StsAuth()且参数为三个，比go的多一个security token。即，go实现auth是后面把security token加在请求头了。
感谢大神回复！
