### ISSUE TITLE
只能通过fake115uploader命令启动吗？每次输入感觉好长，能自行修改启动命令吗？

### ISSUE THREAD

**Issue by dongzideas** [orzogc/fake115uploader#10]
如题

**Comment by orzogc** [comment]
请重命名可执行文件，或者使用自动补全

**Comment by dongzideas** [comment]
感谢，已验证成功。  还请问每次更新的cookie能解决吗？   还是每次登陆都要重新获取，然后修改config

**Comment by orzogc** [comment]
https://github.com/orzogc/fake115uploader/issues/5#issuecomment-710778320
这样做的话浏览器的cookie大概能保持30天有效

**Comment by orzogc** [comment]
或者不重新登陆115网页也能保持cookie 30天有效

**Comment by dongzideas** [comment]
感谢，因为还是经常需要网页重新登陆的，我研究下怎么改那个session吧

**Comment by dongzideas** [comment]
-r参数是有什么问题吗？   我在config里填写  例如 "resultDir": "D:\JJJ\"     提示不符合Jason格式

**Comment by orzogc** [comment]
保存上传结果而已，不需要不用管

**Comment by dongzideas** [comment]
我想使用 -i 批量上传文件的时候，还是需要保留结果的。  目前还不需要查看结果

不好意思，问下修改CID、SEID、UID这三个cookie的Expires / Max-Age，是在浏览器里修改？好像无法编辑的样子

**Comment by orzogc** [comment]
是在浏览器里修改，一般能直接改的，你搜索一下方法吧

**Comment by dongzideas** [comment]
好的感谢
