### ISSUE TITLE
新功能小建议

### ISSUE THREAD

**Issue by mizhewei** [orzogc/fake115uploader#11]
大佬您好，您的工具帮了很大的忙
我想建议一下：能不能出一个docker版本的，可以用在群晖上的，115官方没有适合群晖的客户端
如果可以的话，因为我是个小白，能不能麻烦您再做个简单一点的就可以的教程……
麻烦您啦 非常感谢

**Comment by orzogc** [comment]
Releases的版本应该能直接运行的

**Comment by mizhewei** [comment]
应该怎么运行啊 /小白问号 或者您可以告诉我可能需要的教程关键词 我可以自己搜...

**Comment by orzogc** [comment]
没用过群晖，Linux的话直接下载 https://github.com/orzogc/fake115uploader/releases/download/v0.3.1/fake115uploader-0.3.1-linux-amd64.tar.gz 解压运行即可

**Comment by mizhewei** [comment]
请问解压之后在linux运行的命令是怎么样的a 我不知道该怎么搜索

**Comment by orzogc** [comment]
在解压出来的文件所在文件夹运行`./fake115uploader`

**Comment by mizhewei** [comment]
好的，已经可以运行了 希望能支持遍历本地文件夹上传 一个一个有点麻烦 
辛苦您了 万分感谢
