### ISSUE TITLE
115加解密还可用吗

### ISSUE THREAD

**Issue by ODtian** [orzogc/fake115uploader#12]

**Comment by orzogc** [comment]
可用

**Comment by ODtian** [comment]
https://github.com/orzogc/fake115uploader/blob/12fc388285df0d0ebacf14a97988f250495bd3cd/cipher/cipher.go#L120-L126
这里好像无法解密，我用python版本也是这里不行，是不是密钥不行了，浏览器版本是24.0.0.34

密文是这个`aH1DBXgKcQM8wdZ6jnXJRGq/x3zIyX/rPk1BzkE25jru671UgCtpJ9JQgO4rs3YJWSoe0o1xhbzXErNPRd+WTicfsduy2r0Y8mIryZ2kWZp/Kgia2NjXte+GmYoU0hQnn4yh27Zf+fgsfkMmI2sn/WxaiFqTkjpF6KiCaS8p0qw=`

**Comment by orzogc** [comment]
我这里使用没有问题，要注意`Cipher`加密一次请求只能解密对应的响应
