### ISSUE TITLE
[enhancement] 添加文件夹上传及类Sync功能

### ISSUE THREAD

**Issue by UVJkiNTQ** [orzogc/fake115uploader#2]
0. 目前程序仅支持指定cid的单个文件夹的文件上传，不支持目录/次级目录。
1. 比对源文件及网盘存储文件的modtime/size/hash进行增量/同步。

BTW，搜索类似工具时，发现有个go的轮子，可以看一下。
https://github.com/deadblue/elevengo

**Comment by orzogc** [comment]
第一个不太明白你的意思，次级目录也是要用cid指定
第二个不打算做

**Comment by UVJkiNTQ** [comment]
第一个指的是目录上传（含递归子目录）
