### ISSUE TITLE
上传5G以上文件报错

### ISSUE THREAD

**Issue by UVJkiNTQ** [orzogc/fake115uploader#24]
是115会员账户

日志：
2022/02/23 21:27:31 秒传模式上传文件：XXX
2022/02/23 21:36:56 秒传模式上传 XXX 失败
2022/02/23 21:36:56 现在开始使用普通模式上传 XXX
2022/02/23 21:36:56 普通模式上传文件：XXX
按q键停止上传并退出程序
800.00 KiB / 22.39 GiB [>________________________________________________________] 0.00% ? p/s 100ms
2022/02/23 21:36:57 普通模式上传 XXX 出现错误：ossUploadFile() error: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage="Post body size must be less than 5G.", RequestId=[MARKED]
上传成功的文件（0）：
上传失败的文件（1）：
XXX

**Comment by orzogc** [comment]
你用断点续传模式上传试试

**Comment by UVJkiNTQ** [comment]
solved
原本用的-u，应该用-m
