### ISSUE TITLE
文件夹上传出错 

### ISSUE THREAD

**Issue by mizhewei** [orzogc/fake115uploader#28]
文件夹上传出错 
/centos/fake115/fake115uploader -m -recursive /downloads/kaixmatty/                                                                         
2022/06/13 11:01:29 上传文件夹 /downloads/kaixmatty/ 出现错误：没有创建文件夹 kaixmatty ，取消上传 /downloads/kaixmatty/._14-10-2021.mp4                        
2022/06/13 11:01:30 本次运行没有上传文件

**Comment by mizhewei** [comment]
去掉最后的/就可以了 被自己蠢到了 THX

**Comment by kdurov** [comment]
之前自己上传也发现了如果有 trailing slash 会出错的问题。
希望能把这加到readme里面，不少 shell 自动补全都会自动加上/

**Comment by orzogc** [comment]
修复了
