### ISSUE TITLE
新版api

### ISSUE THREAD

**Issue by ODtian** [orzogc/fake115uploader#3]
通过抓取115浏览器发现新版api的版本已经来到2.0.0.0了，而且在initupload的时候对body部分进行了加密，请问有解密方法的头绪吗，可以一起讨论下

**Comment by orzogc** [comment]
麻烦把地址和响应贴出来

**Comment by ODtian** [comment]
地址都没变，请求参数的appVer变成了2.0.0.0，请求和响应的body都是乱码，应该加密过了

**Comment by himarrin** [comment]
header = {
    "User-Agent": 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 115Browser/9.2.1',
    "Accept-Language": 'zh-CN,zh;q=0.9',
    "Content-Type": 'application/x-www-form-urlencoded',
    "Cookie": COOKIES}

URL = "http://uplb.115.com/3.0/initupload.php?appid=0&appfrom=10&appversion=2.0.0.0&format=json&isp=0&sig=" + \
        sig + "&t=" + str(int(time.time())) + "&topupload=0&rt=0"

postData = "api_version=2.0.0.0&fileid={fileid}&filename={filename}&filesize={filesize}&preid={preid}&target={target}&userid={userid}".format(
        fileid=fileid, filename=filename, filesize=filesize, preid=preid, target=target, userid=user_id)
    r = requests.post(URL, data=postData, headers=header)
亲测可行

**Comment by orzogc** [comment]
加密解密的代码看 https://github.com/orzogc/fake115uploader/blob/master/cipher/cipher.go
