### ISSUE TITLE
关于上传参数

### ISSUE THREAD

**Issue by kdurov** [orzogc/fake115uploader#30]
你好

是否能让运行时默认开启 --recursive 参数呢？
遇到上传文件夹时，不加这个参数会报错结束运行（并不会把文件夹内文件按照单独文件一个个上传）
如果只有单独文件，加上这个参数也没什么影响。

另外能否考虑让参数在命令最后也能正确运行呢？
例如添加上传文件后突然想到需要上传后自动删除本地文件时，在 -m 文件 后面添加 -e 的话 -e 会被当作文件而报错。
或者事后想指定上传的文件夹 -c 时候也会类似报错。

谢谢

**Comment by orzogc** [comment]
因为上传参数支持多个文件，所以文件名必须在最后的位置，不然无法区分文件名和参数
