### ISSUE TITLE
传了一个20g的文件出现了错误

### ISSUE THREAD

**Issue by jerryandtom007** [orzogc/fake115uploader#31]
您好：
出现错误：ossUploadFile() error: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage="Post body size must be less than 5G.", RequestId=631D6856B2D807363161FDD9

是会员帐号，试了下6G的可以正常上传用的 -u 参数，是20g的文件太在了吗？

**Comment by orzogc** [comment]
用`-m`参数，`-u`参数上传的文件不能太大

**Comment by jerryandtom007** [comment]
好哒  谢谢您的回复！
