### ISSUE TITLE
幺幺5已升级，此上传方法已失效。

### ISSUE THREAD

**Issue by yoshyv** [orzogc/fake115uploader#32]
2022/09/28 03:42:39 秒传模式上传文件：archive.zip
2022/09/28 03:42:40 sig的值是：
2022/09/28 03:42:40 秒传模式上传文件 archive.zip 的响应体 的内容是：
{"request":"upload","status":4,"statuscode":403,"statusmsg":"\u8bf7\u5347\u7ea7\u5230\u6700\u65b0\u7248\u672c","pickcode":"","target":"","version":"3.0"}
2022/09/28 03:42:40 秒传模式上传 archive.zip 出现错误：fastUploadFile() error: 秒传模式上传 archive.zip 失败
2022/09/28 03:42:40 现在开始使用断点续传模式上传
2022/09/28 03:42:40 断点续传模式上传文件：archive.zip
2022/09/28 03:42:41 info的值：
{Endpoint:http://oss-cn-shenzhen.aliyuncs.com GetTokenURL:https://uplb.115.com/3.0/gettoken.php}
2022/09/28 03:42:41 OSS token的值：
&{StatusCode:200 AccessKeySecret: SecurityToken: Expiration:2022-09-28T04:42:41Z AccessKeyID: endpoint:http://oss-cn-shenzhen.aliyuncs.com}
2022/09/28 03:42:41 断点续传模式上传 archive.zip 出现错误 ：multipartUploadFile() error: getBucket() error: bucket name  len is between [3-63],now is 0

看403错误提示是让更新版本。
请问能更新修复下么？

谢谢。

**Comment by jerryandtom007** [comment]
是的115似乎对sha1进行了升级

**Comment by orzogc** [comment]
hash没变，应该是请求体和响应体都加密了

**Comment by kdurov** [comment]
有没有linux ssh纯命令行界面其他上传方案了啊😭
定期备份和录制上传这下都卡了没法用了。

**Comment by orzogc** [comment]
模拟网页上传的方式应该还能用，就是上传不了太大的文件而已

**Comment by kdurov** [comment]
fake115uploader有模拟的功吗？另外多大算是大啊。
录制直播的vps每天都有十几到20多g的录制文件，肯定是超了吧。
看隔壁的用115sha1提取的工具貌似也失效了。

**Comment by orzogc** [comment]
> fake115uploader有模拟的功吗？另外多大算是大啊。 录制直播的vps每天都有十几到20多g的录制文件，肯定是超了吧。 看隔壁的用115sha1提取的工具貌似也失效了。

fake115uploader只有很早期的版本才支持模拟网页上传，而且应该只支持最大5G的文件

**Comment by kdurov** [comment]
具体什么版本呢？能在解决新版本之前回滚到那版本吗？
我是想用vps搭个网盘然后用115离线下载，但是不能传文件夹而且经常出错还不能续传，一旦出错只能重来。

**Comment by orzogc** [comment]
> 具体什么版本呢？能在解决新版本之前回滚到那版本吗？ 我是想用vps搭个网盘然后用115离线下载，但是不能传文件夹而且经常出错还不能续传，一旦出错只能重来。

很早期的版本，没在commit里

**Comment by kdurov** [comment]
能否添加下旧版呢？
新版本对策的话可能实现么？虽然看了下115有了deb包但是只能装在桌面环境下。
另外哪怕浏览器都是不能多台同时登录的样子？

**Comment by jerryandtom007** [comment]
我看b4sh(T3rry7f)大佬回复啦... 这是希望的曙光嘛  lol.

**Comment by orzogc** [comment]
你们试试最新的代码，看看能不能上传，不能上传的话加`-v`参数运行，把秒传失败的响应体发上来

**Comment by kdurov** [comment]
```
go: downloading github.com/orzogc/fake115uploader v0.3.3-0.20220929172618-ac3d7e96e0a9
go: downloading github.com/aliyun/aliyun-oss-go-sdk v2.2.5+incompatible
go: downloading github.com/cheggaaa/pb/v3 v3.1.0
go: downloading github.com/eiannone/keyboard v0.0.0-20220611211555-0d226195f203
go: downloading golang.org/x/time v0.0.0-20220922220347-f3bd1da661af
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading golang.org/x/sys v0.0.0-20220928140112-f11e5e49a4ec
go: downloading github.com/aead/ecdh v0.2.0
go: downloading github.com/andreburgaud/crypt2go v1.1.0
go: downloading github.com/pierrec/lz4/v4 v4.1.17
go: downloading github.com/rivo/uniseg v0.4.2
go: downloading golang.org/x/crypto v0.0.0-20220926161630-eccd6366d1be
# github.com/rivo/uniseg
go/pkg/mod/github.com/rivo/uniseg@v0.4.2/properties.go:137:6: missing function body
go/pkg/mod/github.com/rivo/uniseg@v0.4.2/properties.go:137:20: syntax error: unexpected [, expecting (
note: module requires Go 1.18
```

**Comment by user1121114685** [comment]
> 你们试试最新的代码，看看能不能上传，不能上传的话加`-v`参数运行，把秒传失败的响应体发上来

大佬，走歪路了，其实只需要token就行了，不过现在我没有电脑，无法复现。等我回去再复现一下。

**Comment by kdurov** [comment]
顺便问下怎样查看版本啊？没有--version类的参数么？
#30 另外有可能让在命令最后的参数不被识别成上传文件名么

谢了

**Comment by orzogc** [comment]
> > 你们试试最新的代码，看看能不能上传，不能上传的话加`-v`参数运行，把秒传失败的响应体发上来
> 
> 大佬，走歪路了，其实只需要token就行了，不过现在我没有电脑，无法复现。等我回去再复现一下。

T3rry7f大佬逆向应该是115浏览器的代码，token的算法应该没问题，但是浏览器和手机客户端的sig和token的算法好像是不一样的

**Comment by orzogc** [comment]
> 顺便问下怎样查看版本啊？没有--version类的参数么？ #30 另外有可能让在命令最后的参数不被识别成上传文件名么
> 
> 谢了

所以现在能成功上传了吗？
没做查看版本号的参数

**Comment by kdurov** [comment]
> > > 所以现在能成功上传了吗？ 没做查看版本号的参数
> > 
> > 
> > 额没成功啊，一样还是403报错。
> 
> 你用 https://github.com/T3rry7f/Fake115Upload 这个上传试试

不太会用这个。另外这个不是快两年没更新了吗？

**Comment by 362227** [comment]
所以还不能上传吗？有没有其他方法 ？

**Comment by orzogc** [comment]
等等吧

**Comment by 362227** [comment]
你看看这个，刚刚更新了，看看能不能参考 https://github.com/gaoyb7/115drive-webdav/tree/main/115

**Comment by orzogc** [comment]
上传应该没问题了

**Comment by jerryandtom007** [comment]
大佬牛B   就等一个linux的  懒人包啦   lol.

**Comment by iwestlin** [comment]
@orzogc 我试了下导入秒存链接成功了 `fake115uploader -i sha1.txt`
但是导出链接失败了，`fake115uploader -v -c mycid -o out.txt`
提示`很抱歉，提取码不能为空`
```
获取下载地址的响应为 {"state":false,"msg":"\u5f88\u62b1\u6b49\uff0c\u63d0\u53d6\u7801\u4e0d\u80fd\u4e3a\u7a7a\u3002","errno":50001}
```

**Comment by 362227** [comment]
> 大佬牛B 就等一个linux的 懒人包啦 lol.

去gitpod注册，fork下
go install github.com/orzogc/fake115uploader@master
cp /workspace/go/bin/fake115uploader /workspace/fake115uploader

然后就可以下载编译的了

**Comment by jerryandtom007** [comment]
> > 大佬牛B 就等一个linux的 懒人包啦 lol.
> 
> 去gitpod注册，fork下 go install github.com/orzogc/fake115uploader@master cp /workspace/go/bin/fake115uploader /workspace/fake115uploader
> 
> 然后就可以下载编译的了

谢谢 大佬！！！ 打包成功了

**Comment by kdurov** [comment]
115 又犯贱了么？
2022/10/15 23:34:36 秒传模式上传文件：new.zip
2022/10/15 23:34:40 initupload的链接是：
2022/10/15 23:34:40 sig的值是：
2022/10/15 23:34:40 k_ec的值是：
2022/10/15 23:34:41 秒传模式上传文件 new.zip 的响应体的内容是：
{"request":"upload","status":0,"statuscode":0,"statusmsg":"","pickcode":"","target":"","version":"3.0","state":false,"message":"\u4e0a\u4f20\u5931\u8d25","code":10023}

有别人能复现吗？

**Comment by 362227** [comment]
> 115 又犯贱了么？ 2022/10/15 23:34:36 秒传模式上传文件：new.zip 2022/10/15 23:34:40 initupload的链接是： 2022/10/15 23:34:40 sig的值是： 2022/10/15 23:34:40 k_ec的值是： 2022/10/15 23:34:41 秒传模式上传文件 new.zip 的响应体的内容是： {"request":"upload","status":0,"statuscode":0,"statusmsg":"","pickcode":"","target":"","version":"3.0","state":false,"message":"\u4e0a\u4f20\u5931\u8d25","code":10023}
> 
> 有别人能复现吗？

我这正常

**Comment by kdurov** [comment]
> 我这正常

你是国内上传么？还是国外传的？

**Comment by 362227** [comment]
> > 我这正常
> 
> 你是国内上传么？还是国外传的？ 就现在才有的问题，几个小时前传的看上去都成功了。
> 
> 我这用VPS搭的代理上传也一样失败。全部都失败。

国内外都测试了下，国外无法上传，国内可以

**Comment by kdurov** [comment]
> > > 我这正常
> > 
> > 
> > 你是国内上传么？还是国外传的？ 就现在才有的问题，几个小时前传的看上去都成功了。
> > 我这用VPS搭的代理上传也一样失败。全部都失败。
> 
> 国内外都测试了下，国外无法上传，国内可以 国外上传都是这样的错误：`出现错误：multipartUploadFile() error: getBucket() error: bucket name len is between [3-63],now is 0`

115也学会罢工罢课罢免国贼了？🙄

**Comment by 362227** [comment]
> > > > 我这正常
> > > 
> > > 
> > > 你是国内上传么？还是国外传的？ 就现在才有的问题，几个小时前传的看上去都成功了。
> > > 我这用VPS搭的代理上传也一样失败。全部都失败。
> > 
> > 
> > 国内外都测试了下，国外无法上传，国内可以 国外上传都是这样的错误：`出现错误：multipartUploadFile() error: getBucket() error: bucket name len is between [3-63],now is 0`
> 
> 115也学会罢工罢课罢免国贼了？🙄

国内最近都在禁海外ip，百度网盘今天就不能分享了

**Comment by kdurov** [comment]
> > > > > 我这正常
> > > > 
> > > > 
> > > > 你是国内上传么？还是国外传的？ 就现在才有的问题，几个小时前传的看上去都成功了。
> > > > 我这用VPS搭的代理上传也一样失败。全部都失败。
> > > 
> > > 
> > > 国内外都测试了下，国外无法上传，国内可以 国外上传都是这样的错误：`出现错误：multipartUploadFile() error: getBucket() error: bucket name len is between [3-63],now is 0`
> > 
> > 
> > 115也学会罢工罢课罢免国贼了？🙄
> 
> 国内最近都在禁海外ip，百度网盘今天就不能分享了

好家伙，也不知道20大后多久解封。。。。我这没国内IP啊。

**Comment by 362227** [comment]
> > > > > > 我这正常
> > > > > 
> > > > > 
> > > > > 你是国内上传么？还是国外传的？ 就现在才有的问题，几个小时前传的看上去都成功了。
> > > > > 我这用VPS搭的代理上传也一样失败。全部都失败。
> > > > 
> > > > 
> > > > 国内外都测试了下，国外无法上传，国内可以 国外上传都是这样的错误：`出现错误：multipartUploadFile() error: getBucket() error: bucket name len is between [3-63],now is 0`
> > > 
> > > 
> > > 115也学会罢工罢课罢免国贼了？🙄
> > 
> > 
> > 国内最近都在禁海外ip，百度网盘今天就不能分享了
> 
> 好家伙，也不知道20大后多久解封。。。。我这没国内IP啊。

 -http-proxy 设置中国代理ip就可以，传输用海外ip没问题，我刚刚测试了
