### ISSUE TITLE
大佬，后台运行没一会儿就会挂起怎么解决？

### ISSUE THREAD

**Issue by RiverChu0** [orzogc/fake115uploader#33]
### 使用如下命令运行：
```
nohup ./fake115uploader -m -e 新闻联播20221004.mp4 >/dev/null 2>&1 &
```
**不一会儿就被挂起了，如果转成前台运行就可以。查寻网络，有可能跟下面的原因有关。**

>在《Unix 环境高级编程》第9.8节作业控制中讲到，“如果后台程序试图读取终端，这并不是一个错误，但是终端驱动程序将检测这种情况，并向后台作业发送一个特定信号SIGTTIN，该信号会停止此后台程序，并向用户发送通知”

`fake115uploader`里有监听`os.Signal`的代码，对go没研究。不知如何更改？搜索了一遍`Issues`，也没发现相关案例。特此一问，望大佬指点迷津。

经过大佬指点，已解决
# 解决
1. 安装`tmux`
```
sudo yum install tmux
```

2. 创建会话
```
tmux new -s fuck115
```

3. 进入会话
```
tmux attach -t fuck115
```

4. 执行命令
```
/home/admin/115drive/upload.sh
```

5. 退出
按下`Ctrl+b`，松开，再按`d`。退出会话。

**Comment by orzogc** [comment]
用`tmux`之类的工具后台运行
