### ISSUE TITLE
断点续传报错

### ISSUE THREAD

**Issue by UVJkiNTQ** [orzogc/fake115uploader#34]
错误报告：
multipartUploadFile() error: getBucket() error: bucket name  len is between [3-63],now is 0

**Comment by orzogc** [comment]
请问你用的是最新版本吗？

**Comment by UVJkiNTQ** [comment]
go install latest跑过了。
程序好像不会输出版本号……

**Comment by UVJkiNTQ** [comment]
install master可以了，是标签问题吗
