### ISSUE TITLE
使用发现不走socks5流量

### ISSUE THREAD

**Issue by erurudesu** [orzogc/fake115uploader#35]
在json配置proxy为 “socks5://127.0.0.1:8080” 可是上传依旧没有走代理流量，不知道如何解决

**Comment by orzogc** [comment]
哪个proxy？OSS代理不支持SOCKS5

**Comment by erurudesu** [comment]
> 哪个proxy？OSS代理不支持SOCKS5

原来如此，所以-m上传文件都没法使用socks5流量是吗

**Comment by orzogc** [comment]
只有单纯的http请求能用SOCKS5代理，文件上传不能用SOCKS5代理
可以用`privoxy`之类的工具将SOCKS5代理转化为HTTP代理

**Comment by erurudesu** [comment]
> 只有单纯的http请求能用SOCKS5代理，文件上传不能用SOCKS5代理 可以用`privoxy`之类的工具将SOCKS5代理转化为HTTP代理

源码init initialize conn的oss上传组件只写了http，是因为原本就不支持socks5还是因为没写所以不支持？

**Comment by erurudesu** [comment]
> 阿里的官方库不支持SOCKS5代理

感谢解答
