### ISSUE TITLE
vps上传出现错误

### ISSUE THREAD

**Issue by jerryandtom007** [orzogc/fake115uploader#36]
出现错误：ossUploadFile() error: bucket name  len is between [3-63],now is 0

用的-u, 刚刚出现的，前几天还是好用的，试了下本地不会出现错误是可以传的。

**Comment by orzogc** [comment]
应该过几天就好了

**Comment by jerryandtom007** [comment]
> 应该过几天就好了

单纯是20da的原因，墙外受限啦。。。

**Comment by RiverChu0** [comment]
我的也是呢，一觉醒来发现报这个错。原因未知
