### ISSUE TITLE
[提问] 阿里云内网不用付流量钱是吗？

### ISSUE THREAD

**Issue by johnlabor** [orzogc/fake115uploader#37]
你好，一直在关注这个工具，很好用。

我在国外的上传速度不稳，所以就想在阿里云深圳弄一台机器来。

有两个疑问想请您解答：@orzogc

1. 如果阿里云深圳服务器用内网，上传-a不需要额外花费流量费吧？
https://www.alibabacloud.com/help/en/elastic-compute-service/latest/public-bandwidth

2. 如果这样的话，那我直接在阿里云服务器上传，和在国外用这个-a 结合 -http-proxy指向阿里云服务器，是否是一样的效果呢？如果后者可以的话，就能省点阿里云硬盘费用，我就买个小点的服务器，直接改成proxy server就行了。

谢谢了。

**Comment by orzogc** [comment]
第一个问题，阿里云内网流量不用钱
第二个问题，后者我没试过，不知道行不行，建议你先测试一下

**Comment by johnlabor** [comment]
好的我会测试，另外再咨询两个问题。

1. 看到另外一个issue讲述了用默认分块10000块太多的问题，导致过多http连接。
我现在传一个30G左右的大文件，已经传了一大半，还能再用-parts-num进行降低分块的吗？我主要怕会导致上传的文件不完整。

2. 如果我上传一个文件一半，然后不再上传，已经上传的部分在115是看不到，如何能把remote那边上传的部分删除？
如果使用客户端，就可以直接删掉任务，用这个工具貌似没有这项功能。

谢了。

**Comment by orzogc** [comment]
> 好的我会测试，另外再咨询两个问题。
> 
>     1. 看到另外一个issue讲述了用默认分块10000块太多的问题，导致过多http连接。
>        我现在传一个30G左右的大文件，已经传了一大半，还能再用-parts-num进行降低分块的吗？我主要怕会导致上传的文件不完整。
> 
>     2. 如果我上传一个文件一半，然后不再上传，已经上传的部分在115是看不到，如何能把remote那边上传的部分删除？
>        如果使用客户端，就可以直接删掉任务，用这个工具貌似没有这项功能。
> 
> 
> 谢了。

第一个问题，上传到一半不能改分块（改了也没用），不用担心文件完整性，会有校验的
第二个问题，不需要删除，115官方那边大概会处理吧，未上传成功的文件不会占用你帐号的空间

**Comment by johnlabor** [comment]
好的，非常感谢您回答了我所有问题，issue closed.

**Comment by 362227** [comment]
> 好的，非常感谢您回答了我所有问题，issue closed.



> 你好，一直在关注这个工具，很好用。
> 
> 我在国外的上传速度不稳，所以就想在阿里云深圳弄一台机器来。
> 
> 有两个疑问想请您解答：@orzogc
> 
> 1. 如果阿里云深圳服务器用内网，上传-a不需要额外花费流量费吧？
>    https://www.alibabacloud.com/help/en/elastic-compute-service/latest/public-bandwidth
> 2. 如果这样的话，那我直接在阿里云服务器上传，和在国外用这个-a 结合 -http-proxy指向阿里云服务器，是否是一样的效果呢？如果后者可以的话，就能省点阿里云硬盘费用，我就买个小点的服务器，直接改成proxy server就行了。
> 
> 谢谢了。

 -http-proxy有没有用啊，能不能省流量？

**Comment by orzogc** [comment]
> -http-proxy有没有用啊，能不能省流量？

`-http-proxy`是流量走http代理，不能省流量

**Comment by free-150** [comment]
> 好的我会测试，另外再咨询两个问题。
> 
>     1. 看到另外一个issue讲述了用默认分块10000块太多的问题，导致过多http连接。
>        我现在传一个30G左右的大文件，已经传了一大半，还能再用-parts-num进行降低分块的吗？我主要怕会导致上传的文件不完整。
> 
>     2. 如果我上传一个文件一半，然后不再上传，已经上传的部分在115是看不到，如何能把remote那边上传的部分删除？
>        如果使用客户端，就可以直接删掉任务，用这个工具貌似没有这项功能。
> 
> 
> 谢了。

请问你第二个成功了吗？我跟你一样的需求，但是试了下没成功无法走内网

**Comment by free-150** [comment]
> 你好，一直在关注这个工具，很好用。
> 
> 我在国外的上传速度不稳，所以就想在阿里云深圳弄一台机器来。
> 
> 有两个疑问想请您解答：@orzogc
> 
>     1. 如果阿里云深圳服务器用内网，上传-a不需要额外花费流量费吧？
>        https://www.alibabacloud.com/help/en/elastic-compute-service/latest/public-bandwidth
> 
>     2. 如果这样的话，那我直接在阿里云服务器上传，和在国外用这个-a 结合 -http-proxy指向阿里云服务器，是否是一样的效果呢？如果后者可以的话，就能省点阿里云硬盘费用，我就买个小点的服务器，直接改成proxy server就行了。
> 
> 
> 谢谢了。

请问你第二个成功了吗？我跟你一样的需求，但是试了下没成功无法走内网
