### ISSUE TITLE
Win10上传完不会自动退出

### ISSUE THREAD

**Issue by cafrew** [orzogc/fake115uploader#38]
用这条命令上传：
> fake115uploader -m "F:\文件.zip"

log如下：
> 2022/11/13 09:37:36 秒传模式上传文件：F:\文件.zip
> 2022/11/13 09:38:00 秒传模式上传 F:\文件.zip 出现错误：秒传模式上传 F:\文件.zip 失败
> 2022/11/13 09:38:00 现在开始使用断点续传模式上传
> 2022/11/13 09:38:00 断点续传模式上传文件：F:\文件.zip
> 4.45 GiB / 4.45 GiB [---------------------------------------------------] 100.00% 5.02 MiB p/s 15m8s
> 2022/11/13 09:53:10 断点续传模式上传 F:\文件.zip 成功

到这一步时就会卡住，不会返回，要点一下命令行窗口使其变成当前窗口才会返回
尝试了这些方法，没有作用：
1. echo. | fake115uploader -m "F:\文件.zip"
2. fake115uploader -m "F:\文件.zip" <带有回车的文本文档.txt
3. start cmd /c "fake115uploader -m "F:\文件.zip" "

环境是Win10的cmd命令行
有任何帮助都可以回复的，非常感谢

**Comment by orzogc** [comment]
用powershell试试？

**Comment by cafrew** [comment]
尝试了这个cmd命令：
> start powershell -command ".\fake115uploader -m \"F:\文件.zip\" "

还是卡在这里
> 2022/11/13 16:21:58 断点续传模式上传 F:\文件.zip 成功

要点一下Powershell窗口才会返回

**Comment by orzogc** [comment]
不清楚为啥这样

**Comment by cafrew** [comment]
v0.4版没有这个问题，但是会出现下面的错误
> error: bucket name  len is between [3-63],now is 0

v0.5版没有bucket name错误但是不能返回，可以比较一下看看是哪里变了吗

**Comment by orzogc** [comment]
没什么大的变化，0.4版本只是直接panic而已

**Comment by cafrew** [comment]
可以告诉我0.4版本panic的地方在哪里吗，我看看0.5是怎么处理的，然后搬到0.4上面，看看能不能继续用

**Comment by cafrew** [comment]
我找了一下记录，10月16日用0.4版本可以正常上传和退出，11月6日用0.4出现bucket name 错误，我下载0.5使用，出现了上传成功不能返回的问题

**Comment by orzogc** [comment]
10月16日0.4版本不可能正常上传吧？

**Comment by cafrew** [comment]
看错了，实际上传是8月30，10月16我修改了文件，看成上传时间了

**Comment by cafrew** [comment]
自己写了个脚本每分钟激活一下命令行窗口，简单粗暴地解决了🤣

**Comment by RiverChu0** [comment]
同样的问题，上传完成后。窗口必须处于激活，才会返回。试了一下windows下的ubuntu可以解决，但上传网速和直接在命令行差很多，属于难以忍受级别。

**Comment by canwushuang** [comment]
```func main() {
	defer func() {
		if len(result.Failed) != 0 {
			os.Exit(1)
		}
	}()

	go handleQuit()

	err := initialize()
	checkErr(err)

	// ctx, cancel := context.WithCancel(context.Background())
	// defer cancel()
	// go getInput(ctx)
	defer keyboard.Close()

	defer exitPrint()```
main.go func main()函数中注释掉上述3行，目的是取消键盘监听退出事件。
##缺点是无法手动操作输入中断按键行为。如果用在win上自动化，也就不需要额外输入退出行为的监听了。
修改后直接 cd 到源码根目录 go install即可。
