### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by lloyd18** [orzogc/fake115uploader#4]
怎么用？

**Comment by orzogc** [comment]
看说明 https://github.com/orzogc/fake115uploader#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
windows下可以用PowerShell运行

**Comment by lloyd18** [comment]
> 看说明 https://github.com/orzogc/fake115uploader#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
> 
> windows下可以用PowerShell运行

感谢！在Debian下用的，准备睡了，明天研究一下。

**Comment by orzogc** [comment]
现在你会用了吗？

**Comment by lloyd18** [comment]
> 现在你会用了吗？

已经用上了，上传有点慢。美国VPS 350KB/s左右，编译安装遇到点问题，报错
`../go/src/github.com/orzogc/fake115uploader/main.go:436:10: undefined: errors.Is
../go/src/github.com/orzogc/fake115uploader/main.go:454:9: undefined: errors.Is
../go/src/github.com/orzogc/fake115uploader/multipart.go:233:20: undefined: errors.Is`
后来下载打包好的，但不会解压.7z，手动解压完再上传就好了，建议linux压缩包格式改成zip或tar.gz

**Comment by lloyd18** [comment]
> 现在你会用了吗？

因为太慢了，所以特地开了个阿里云轻量云试一下内网传输，不过好像没效果，不知道是不是命令不对？
`./fake115uploader -m xxx.mp4 -a`

**Comment by orzogc** [comment]
> > 现在你会用了吗？
> 
> 已经用上了，上传有点慢。美国VPS 350KB/s左右，编译安装遇到点问题，报错
> `../go/src/github.com/orzogc/fake115uploader/main.go:436:10: undefined: errors.Is ../go/src/github.com/orzogc/fake115uploader/main.go:454:9: undefined: errors.Is ../go/src/github.com/orzogc/fake115uploader/multipart.go:233:20: undefined: errors.Is`
> 后来下载打包好的，但不会解压.7z，手动解压完再上传就好了，建议linux压缩包格式改成zip或tar.gz

你的go版本太旧，请用最新的版本
内网上传需要编译最新的代码

**Comment by lloyd18** [comment]
更新了go版本，运行go get -u github.com/orzogc/fake115uploader 后应该怎么做？目录下没产生任何文件。

**Comment by orzogc** [comment]
> 更新了go版本，运行go get -u github.com/orzogc/fake115uploader 后应该怎么做？目录下没产生任何文件。

在~/go/bin那里
你现在可以用刚发布的0.3版本

**Comment by lloyd18** [comment]
嗯，好像0.3本吧也不能内外上传 @orzogc

**Comment by orzogc** [comment]
> 嗯，好像0.3本吧也不能内外上传 @orzogc

你的阿里云服务器是哪里的？不能上传说明115在你服务器所在地域没有oss服务器，所以不能用内网上传
在服务器上运行`curl https://uplb.115.com/3.0/getuploadinfo.php`看看返回的oss的地域是不是和你的服务器一样？

**Comment by orzogc** [comment]
> 普通模式上传 xxxx.mp4 出现错误：ossUploadFile() error: Put "http://fhnfile.oss-cn-shenzhen-internal.aliyuncs.com/xxxxx": dial tcp 100.118.78.3:80: i/o timeout

好像只有断点续传才能内网上传

**Comment by lloyd18** [comment]
> > 普通模式上传 xxxx.mp4 出现错误：ossUploadFile() error: Put "http://fhnfile.oss-cn-shenzhen-internal.aliyuncs.com/xxxxx": dial tcp 100.118.78.3:80: i/o timeout
> 
> 好像只有断点续传才能内网上传

`{"endpoint":"http:\/\/oss-cn-shenzhen.aliyuncs.com","gettokenurl":"https:\/\/uplb.115.com\/3.0\/gettoken.php"}`

**Comment by lloyd18** [comment]
国内阿里云轻量

**Comment by lloyd18** [comment]
断点续传也试了，还是报这个错误

**Comment by orzogc** [comment]
说明115在阿里云香港没有oss服务器，你用国内的应该就可以上传了

**Comment by lloyd18** [comment]
这就有点尴尬了，用国内的上不了外网，很多资源下不了

**Comment by orzogc** [comment]
你没有其他问题了吧？
