### ISSUE TITLE
文件名长度识别存在问题

### ISSUE THREAD

**Issue by duskNNNN** [orzogc/fake115uploader#41]
![图片](https://user-images.githubusercontent.com/94543546/206841635-6d2bde39-c9ea-4092-9e57-eb7ba286cfed.png)
我这个文件名长度是55，但却识别成0，希望作者大大能修复一下

**Comment by duskNNNN** [comment]
可能是官方的问题，发现用115客户端也上传不了
![图片](https://user-images.githubusercontent.com/94543546/206842348-c456e9f1-c866-423f-9c47-2be4ebd8a8e9.png)

**Comment by orzogc** [comment]
不是文件名的问题
