### ISSUE TITLE
上传结束后生成 hashlink

### ISSUE THREAD

**Issue by kdurov** [orzogc/fake115uploader#43]
请问有办法再上传原创文件后自动生成 hashlink 备用吗？
现在版本如果同时用 `-b -m/u` 上传之后，的确可以生成，但是会在上传结束后重新反复计算hash值。
请问能有办法跳过反复计算过程吗？
毕竟上传之前秒传模式测过一次。

**Comment by orzogc** [comment]
目前没办法跳过

**Comment by kdurov** [comment]
可以利用 -c cid -o sha1.txt 这样获取就不用重新反复计算么？
-c 因为只能指定文件夹，单个文件不知道有没有什么好办法？

**Comment by orzogc** [comment]
hashlink已经没用了
