### ISSUE TITLE
上传出现错误

### ISSUE THREAD

**Issue by vvlaw** [orzogc/fake115uploader#44]
出现错误：ossUploadFile() error: bucket name  len is between [3-63],now is 0

**Comment by orzogc** [comment]
确定cookies没问题？

**Comment by vvlaw** [comment]
cookies 应该是问题的，我又重新设置了遍。

VPS在海外，是的，美国的服务器。不过之前可以用，不知道为什么这次不行。

**Comment by vvlaw** [comment]
2023/01/05 03:38:19 请确定网络是否畅通或者cookies是否设置好，每一次 登陆网页端115都要重设一次cookies
panic: initialize() error: getUserKey() error: 获取userkey出错，请确定cookies是否设置好

没设置好cookie的话，应该会有这样的提示的？

**Comment by orzogc** [comment]
应该是115官方又开始限制海外IP上传了

**Comment by vvlaw** [comment]
> 应该是115官方又开始限制海外IP上传了

又感觉不像，前两天刚刚用的，一切正常，只不过我恢复了vps的备份后，重新安装了fake115uploader,结果就遇到问题了。

不知道还有没有兄弟有海外的vps可以测试一下？还在考虑要不要续115的永V呢？现在如果这个功能都不能用了，感觉也没多大用处了。

**Comment by kdurov** [comment]
目前没有限制海外IP的。
光看
`ossUploadFile() error: bucket name len is between [3-63],now is 0`
这个错误没用的。上传时候 `-v `参数看具体哪部出错。资源被屏蔽上传，文件名含有不能用的字符都是这个报错。

**Comment by vvlaw** [comment]
谢谢

2023/01/07 02:43:43 请确定网络是否畅通或者cookies是否设置好，每一次登陆网 页端115都要重设一次cookies
panic: initialize() error: getUserKey() error: Get "
https://proapi.115.com/app/uploadinfo": net/http: TLS handshake timeout

goroutine 1 [running]:
main.checkErr(...)
        ***@***.***/main.go:83
main.main()
        /root/go/pkg/mod/
***@***.***/main.go:399 +0x119

这是cookie错误吗？

**Comment by vvlaw** [comment]
> 目前没有限制海外IP的。 光看 `ossUploadFile() error: bucket name len is between [3-63],now is 0` 这个错误没用的。 上传时候 `-v `参数看具体哪步出错。 资源被屏蔽上传，文件名含有不能用的字符都是这个报错。
> 
> 另外永v怎么来的续费一说？

2023/01/07 05:11:04 Cookies的值为：USERSESSIONID=***********************************************************************************************************************************************************************************************************************130
2023/01/07 05:11:05 userID和userKey的值分别是：5********3 2D******************************A3
2023/01/07 05:11:07 排序文件夹 0 成功
2023/01/07 05:11:09 本次运行没有上传文件
[root@vvlaw 91videos]# fake115uploader -u *
2023/01/07 05:11:19 秒传模式上传文件：vv.txt
2023/01/07 05:11:21 秒传模式上传 vv.txt 出现错误：fastUploadFile() error: 秒传模式上传 vv.txt 失败
2023/01/07 05:11:21 现在开始使用普通模式上传 vv.txt
2023/01/07 05:11:21 普通模式上传文件：vv.txt
2023/01/07 05:11:23 普通模式上传 vv.txt 出现错误：ossUploadFile() error: bucket name  len is between [3-63],now is 0
上传成功的文件（0）：
上传失败的文件（1）：
vv.txt
保存上传进度的文件（0）：


#########
刚刚又用-v测了新的cookie, 
2023/01/07 05:11:05 userID和userKey的值分别是：5********3 2D******************************A3
2023/01/07 05:11:07 排序文件夹 0 成功
2023/01/07 05:11:09 本次运行没有上传文件
有这个结果，应该是说cookie是正确的。
而这个vv.txt里面只有一个字符，这样的文件也被屏蔽上传？这个文件名应该没有含有不能用的字符吧？

永V现在还可以冲，不过快要关闭了。大多数用vps上传资源给它，如果不能用，现在还有11年的vip也蛮够用的了。

**Comment by vvlaw** [comment]
> 应该是115官方又开始限制海外IP上传了

[root@vvlaw ~]# fake115uploader -v -u wireguard-install.sh
2023/01/07 05:19:36 Cookies的值为：U*******************************************************30
2023/01/07 05:19:37 userID和userKey的值分别是：
2023/01/07 05:19:39 排序文件夹 0 成功
2023/01/07 05:19:40 秒传模式上传文件：wireguard-install.sh
2023/01/07 05:19:40 sig的值是：A*************************************************D
2023/01/07 05:19:41 秒传模式上传文件 wireguard-install.sh 的响应体的内容是：
{"request":"upload","status":4,"statuscode":403,"statusmsg":"\u8bf7\u5347\u7ea7\u5230\u6700\u65b0\u7248\u672c","pickcode":"","target":"","version":"3.0"}
2023/01/07 05:19:41 秒传模式上传 wireguard-install.sh 出现错误：fastUploadFile() error: 秒传模式上传 wireguard-install.sh 失败
2023/01/07 05:19:41 现在开始使用普通模式上传 wireguard-install.sh
2023/01/07 05:19:41 普通模式上传文件：wireguard-install.sh
2023/01/07 05:19:41 info的值：
{Endpoint:http://oss-cn-shenzhen.aliyuncs.com GetTokenURL:https://uplb.115.com/3.0/gettoken.php}
2023/01/07 05:19:42 OSS token的值：
&{StatusCode:200 AccessKeySecret:GLP2daKS29ZWzrSUk844H598JMkkd5GHWSe2GKHvwUPa SecurityToken:CAISkwJ1q6Ft5B2yfSjIr5aEEf3F34lO8PHZNHTj10M3WvxNmfT9pDz2IH9IenVqCOsfsv8ylWxZ7/wflol4RZRJHxSUMZot4skJrA6vPdTM5MC74+0K2c36RzSfAkZ7FC1t072rIunGc9KBNnrm9EYqs5aYGBymW1u6S+7r7bdsctUQWCShcDNCH604DwB+qcgcRxCzXLTXRXyMuGfLC1dysQdRkH527b/FoveR8R3Dllb3uIR3zsbTWsH9M5E8ZcoiDIrphLcqKPv7vXQOu0QQxsBfl7dZ/DrLhNaZDmRK7g+OW+iuqYIzclMjN/NjR/UZ/aStzKcloJCKztnq0xJKNO1ZXirWWYS82szAFfMMyT/IkGwQURqAAWDoTKqjgDAxLHPQOtjlRiO4JWuiZUMvpddzN0BwLE2iHsrQpE7AWybHNanKJ8qs4Xryc5nzUP0Gc/6KPbmGDZWIQUFVk3/F3Rq3HYWT8X3hG8DmXgZlhL8tsvZvw93FBp/lDQ+saHIlR6avDbFChflntuQwngpRTd/R0p3kSl3o Expiration:2023-01-07T06:19:42Z AccessKeyID:STS.NU1ZGq4VoG326RR4CbVsav5VF endpoint:http://oss-cn-shenzhen.aliyuncs.com}
2023/01/07 05:19:42 普通模式上传 wireguard-install.sh 出现错误：ossUploadFile() error: bucket name  len is between [3-63],now is 0
上传成功的文件（0）：
上传失败的文件（1）：
wireguard-install.sh
保存上传进度的文件（0）：



麻烦看看，这是哪里出现了问题？谢谢！

**Comment by orzogc** [comment]
> > 应该是115官方又开始限制海外IP上传了
> 
> [root@vvlaw ~]# fake115uploader -v -u wireguard-install.sh 2023/01/07 05:19:36 Cookies的值为：U******_************************************************30 2023/01/07 05:19:37 userID和userKey的值分别是： 2023/01/07 05:19:39 排序文件夹 0 成功 2023/01/07 05:19:40 秒传模式上传文件：wireguard-install.sh 2023/01/07 05:19:40 sig的值是：A************************************************_D 2023/01/07 05:19:41 秒传模式上传文件 wireguard-install.sh 的响应体的内容是： {"request":"upload","status":4,"statuscode":403,"statusmsg":"\u8bf7\u5347\u7ea7\u5230\u6700\u65b0\u7248\u672c","pickcode":"","target":"","version":"3.0"} 2023/01/07 05:19:41 秒传模式上传 wireguard-install.sh 出现错误：fastUploadFile() error: 秒传模式上传 wireguard-install.sh 失败 2023/01/07 05:19:41 现在开始使用普通模式上传 wireguard-install.sh 2023/01/07 05:19:41 普通模式上传文件：wireguard-install.sh 2023/01/07 05:19:41 info的值： {Endpoint:http://oss-cn-shenzhen.aliyuncs.com GetTokenURL:[https://uplb.115.com/3.0/gettoken.php}](https://uplb.115.com/3.0/gettoken.php%7D) 2023/01/07 05:19:42 OSS token的值： &{StatusCode:200 AccessKeySecret:GLP2daKS29ZWzrSUk844H598JMkkd5GHWSe2GKHvwUPa SecurityToken:CAISkwJ1q6Ft5B2yfSjIr5aEEf3F34lO8PHZNHTj10M3WvxNmfT9pDz2IH9IenVqCOsfsv8ylWxZ7/wflol4RZRJHxSUMZot4skJrA6vPdTM5MC74+0K2c36RzSfAkZ7FC1t072rIunGc9KBNnrm9EYqs5aYGBymW1u6S+7r7bdsctUQWCShcDNCH604DwB+qcgcRxCzXLTXRXyMuGfLC1dysQdRkH527b/FoveR8R3Dllb3uIR3zsbTWsH9M5E8ZcoiDIrphLcqKPv7vXQOu0QQxsBfl7dZ/DrLhNaZDmRK7g+OW+iuqYIzclMjN/NjR/UZ/aStzKcloJCKztnq0xJKNO1ZXirWWYS82szAFfMMyT/IkGwQURqAAWDoTKqjgDAxLHPQOtjlRiO4JWuiZUMvpddzN0BwLE2iHsrQpE7AWybHNanKJ8qs4Xryc5nzUP0Gc/6KPbmGDZWIQUFVk3/F3Rq3HYWT8X3hG8DmXgZlhL8tsvZvw93FBp/lDQ+saHIlR6avDbFChflntuQwngpRTd/R0p3kSl3o Expiration:2023-01-07T06:19:42Z AccessKeyID:STS.NU1ZGq4VoG326RR4CbVsav5VF endpoint:[http://oss-cn-shenzhen.aliyuncs.com}](http://oss-cn-shenzhen.aliyuncs.com%7D) 2023/01/07 05:19:42 普通模式上传 wireguard-install.sh 出现错误：ossUploadFile() error: bucket name len is between [3-63],now is 0 上传成功的文件（0）： 上传失败的文件（1）： wireguard-install.sh 保存上传进度的文件（0）：
> 
> 麻烦看看，这是哪里出现了问题？谢谢！

请问你用的是最新版本吗？

**Comment by orzogc** [comment]
你用115官方的应用看看能不能上传文件

**Comment by vvlaw** [comment]
> > > 应该是115官方又开始限制海外IP上传了
> > 
> > 
> > [root@vvlaw ~]# fake115uploader -v -u wireguard-install.sh 2023/01/07 05:19:36 Cookies的值为：U******_************************************************30 2023/01/07 05:19:37 userID和userKey的值分别是： 2023/01/07 05:19:39 排序文件夹 0 成功 2023/01/07 05:19:40 秒传模式上传文件：wireguard-install.sh 2023/01/07 05:19:40 sig的值是：A************************************************_D 2023/01/07 05:19:41 秒传模式上传文件 wireguard-install.sh 的响应体的内容是： {"request":"upload","status":4,"statuscode":403,"statusmsg":"\u8bf7\u5347\u7ea7\u5230\u6700\u65b0\u7248\u672c","pickcode":"","target":"","version":"3.0"} 2023/01/07 05:19:41 秒传模式上传 wireguard-install.sh 出现错误：fastUploadFile() error: 秒传模式上传 wireguard-install.sh 失败 2023/01/07 05:19:41 现在开始使用普通模式上传 wireguard-install.sh 2023/01/07 05:19:41 普通模式上传文件：wireguard-install.sh 2023/01/07 05:19:41 info的值： {Endpoint:http://oss-cn-shenzhen.aliyuncs.com GetTokenURL:[https://uplb.115.com/3.0/gettoken.php}](https://uplb.115.com/3.0/gettoken.php%7D) 2023/01/07 05:19:42 OSS token的值： &{StatusCode:200 AccessKeySecret:GLP2daKS29ZWzrSUk844H598JMkkd5GHWSe2GKHvwUPa SecurityToken:CAISkwJ1q6Ft5B2yfSjIr5aEEf3F34lO8PHZNHTj10M3WvxNmfT9pDz2IH9IenVqCOsfsv8ylWxZ7/wflol4RZRJHxSUMZot4skJrA6vPdTM5MC74+0K2c36RzSfAkZ7FC1t072rIunGc9KBNnrm9EYqs5aYGBymW1u6S+7r7bdsctUQWCShcDNCH604DwB+qcgcRxCzXLTXRXyMuGfLC1dysQdRkH527b/FoveR8R3Dllb3uIR3zsbTWsH9M5E8ZcoiDIrphLcqKPv7vXQOu0QQxsBfl7dZ/DrLhNaZDmRK7g+OW+iuqYIzclMjN/NjR/UZ/aStzKcloJCKztnq0xJKNO1ZXirWWYS82szAFfMMyT/IkGwQURqAAWDoTKqjgDAxLHPQOtjlRiO4JWuiZUMvpddzN0BwLE2iHsrQpE7AWybHNanKJ8qs4Xryc5nzUP0Gc/6KPbmGDZWIQUFVk3/F3Rq3HYWT8X3hG8DmXgZlhL8tsvZvw93FBp/lDQ+saHIlR6avDbFChflntuQwngpRTd/R0p3kSl3o Expiration:2023-01-07T06:19:42Z AccessKeyID:STS.NU1ZGq4VoG326RR4CbVsav5VF endpoint:[http://oss-cn-shenzhen.aliyuncs.com}](http://oss-cn-shenzhen.aliyuncs.com%7D) 2023/01/07 05:19:42 普通模式上传 wireguard-install.sh 出现错误：ossUploadFile() error: bucket name len is between [3-63],now is 0 上传成功的文件（0）： 上传失败的文件（1）： wireguard-install.sh 保存上传进度的文件（0）：
> > 麻烦看看，这是哪里出现了问题？谢谢！
> 
> 请问你用的是最新版本吗？

不好意思，用最新git版本的成功了。。。谢谢！
