### ISSUE TITLE
解决每次重新登录115时 Cookie变化

### ISSUE THREAD

**Issue by lloyd18** [orzogc/fake115uploader#5]
分享一个插件，可以自动同步Cookie，重启浏览器不用重新登录。

[https://github.com/Andiedie/sync-my-cookie](https://github.com/Andiedie/sync-my-cookie)

**Comment by orzogc** [comment]
不用这么麻烦，登陆115网页后将`CID`、`SEID`、`UID`这三个cookie的`Expires / Max-Age`从`Session`改成离现在比较远的日期就可以了

**Comment by leonsyc** [comment]
> 不用这么麻烦，登陆115网页后将`CID`、`SEID`、`UID`这三个cookie的`Expires / Max-Age`从`Session`改成离现在比较远的日期就可以了

这个方法好像还是会每月被登出。有没有永不登出的办法呢？

**Comment by orzogc** [comment]
> > 不用这么麻烦，登陆115网页后将`CID`、`SEID`、`UID`这三个cookie的`Expires / Max-Age`从`Session`改成离现在比较远的日期就可以了
> 
> 这个方法好像还是会每月被登出。有没有永不登出的办法呢？

用115 app的cookie

**Comment by leonsyc** [comment]
> > > 不用这么麻烦，登陆115网页后将`CID`、`SEID`、`UID`这三个cookie的`Expires / Max-Age`从`Session`改成离现在比较远的日期就可以了
> > 
> > 
> > 这个方法好像还是会每月被登出。有没有永不登出的办法呢？
> 
> 用115 app的cookie

UA和别的headers验证码？json里面能加吗

**Comment by orzogc** [comment]
> > > > 不用这么麻烦，登陆115网页后将`CID`、`SEID`、`UID`这三个cookie的`Expires / Max-Age`从`Session`改成离现在比较远的日期就可以了
> > > 
> > > 
> > > 这个方法好像还是会每月被登出。有没有永不登出的办法呢？
> > 
> > 
> > 用115 app的cookie
> 
> UA和别的headers验证吗？json里面能加吗

没试过，但app的cookie应该是能用的
