### ISSUE TITLE
有几个问题想问问

### ISSUE THREAD

**Issue by free-150** [orzogc/fake115uploader#52]
1. 我使用的是阿里云深圳的轻量服务器也开通了同是深圳区域的Oss，使用命令：fake115uploader -r ./115fake -recursive -a -u /path/to/dir 这样的命令感觉带宽还是占满了，好像并没有使用内网上传。我文件都是小5-50m的小文件，且大部分都可以秒传。
2. 以后会提供arm版的么？

<img width="1318" alt="图片" src="https://github.com/orzogc/fake115uploader/assets/92285544/46575ca1-25fa-4dba-829e-8d6d116db09e">

**Comment by orzogc** [comment]
1. 能上传（非秒传）肯定是用了内网
2. arm应该是支持的，但是你得自己编译
