### ISSUE TITLE
上传名字带括号的文件夹会报错

### ISSUE THREAD

**Issue by reF1nd** [orzogc/fake115uploader#54]
使用`-recursive`参数上传名字带有英文半角括号的文件夹时，初次创建文件夹的时候没问题，可以成功创建。再次执行相同命令时（由于使用了参数`-e`，上传任务完成后我习惯再执行一次相同的命令用于验证有没有漏传的或者上传失败的文件），验证到名字带有括号的文件夹会报错：
`上传文件夹 xxx 出现错误：createDir() error: getURLJSON() error: cannot parse JSON: cannot parse empty string; unparsed tail: ""`
程序就退出了

**Comment by orzogc** [comment]
Linux下测试没有出现这个问题

**Comment by reF1nd** [comment]
> Linux下测试没有出现这个问题

我这边也是Linux，首次上传（首次创建文件夹）是没问题，但再次执行相同命令（跳过已存在的文件夹）的时候，如果已存在的这个文件夹名含有英文半角符号，就会报错。
`2023/07/15 16:27:18 文件夹 sub 已存在，cid：2678456994897067262
2023/07/15 16:27:18 文件夹 [VCB-Studio] Full Metal Panic？ Fumoffu [Hi10p_720p] 已存在，cid：2678456997010996488
2023/07/15 16:27:19 文件夹 sub 已存在，cid：2678456999124925713
2023/07/15 16:27:20 文件夹 [2005] AIR 已存在，cid：2678457008830545205
2023/07/15 16:27:20 上传文件夹 /root/GD 出现错误：createDir() error: getURLJSON() error: cannot parse JSON: cannot parse empty string; unparsed tail: ""
2023/07/15 16:27:21 本次运行没有上传文件`

**Comment by orzogc** [comment]
这个跟括号没关系，主要就是文件夹名字太短导致搜索不会返回这个文件夹，用网页版试试就知道了

**Comment by orzogc** [comment]
请用最新的代码，应该没问题了

**Comment by reF1nd** [comment]
> 请用最新的代码，应该没问题了

我编译测试了最新版，仍然报错。

另外文件夹名不短，也不是新建的文件夹。
导致报错的文件夹名：
`[ANK-Raws] AIR (BDrip x264 FLACx2 5.1ch AC3 VFR Hi10P SUP)`

**Comment by orzogc** [comment]
应该可以了
