### ISSUE TITLE
0.3版增加的上传成功后自动删除本地文件功能出错

### ISSUE THREAD

**Issue by zxhpipi** [orzogc/fake115uploader#6]
在上传成功后自动删除本地文件提示报错
秒传模式上传文件：KAR-038.mp4
2020/12/01 13:07:23 秒传模式上传 KAR-038.mp4 出现错误：秒传模式上传 KAR-038.mp4 失败
2020/12/01 13:07:23 现在开始使用断点续传模式上传
2020/12/01 13:07:23 断点续传模式上传文件：KAR-038.mp4
按q键停止上传并退出程序，断点续传模式会自动保存上传进度
3.09 GiB / 3.09 GiB [----------------------------------------------------------------------] 100.00% 2.64 MiB p/s 20m0s 2020/12/01 13:27:27 断点续传模式上传 KAR-038.mp4 成功
2020/12/01 13:27:27 断点续传模式上传 KAR-038.mp4 出现错误：multipartUploadFile() error: 删除原文件 KAR-038.mp4 出现错误
：remove KAR-038.mp4: The process cannot access the file because it is being used by another process.

**Comment by orzogc** [comment]
麻烦试试最新的代码

**Comment by zxhpipi** [comment]
我用的windows系统

Microsoft Windows [版本 10.0.17763.316]
(c) 2018 Microsoft Corporation。保留所有权利。

S:\DMM-H265\等待上传>E:\IKU\115-up\fake115uploader -e -m -c 1967379380500216211 -r E:\IKU\115-up KRMV-567.mp4
2020/12/01 20:04:10 发现文件 KRMV-567.mp4 的上传曾经中断过，现在开始断点续传
2020/12/01 20:04:10 断点续传模式上传文件：KRMV-567.mp4
按q键停止上传并退出程序，断点续传模式会自动保存上传进度
1.78 GiB / 1.78 GiB [---------------------------------------------------------------------] 100.00% 11.32 MiB p/s 2m41s
2020/12/01 20:06:55 断点续传模式上传 KRMV-567.mp4 成功
2020/12/01 20:06:55 删除存档文件 E:\IKU\115-up\KRMV-567.mp4.json
2020/12/01 20:06:55 断点续传模式上传 KRMV-567.mp4 出现错误：multipartUploadFile() error: 删除原文件 KRMV-567.mp4 出现错 误：remove KRMV-567.mp4: The process cannot access the file because it is being used by another process.
2020/12/01 20:06:56 上传结果保存在 E:\IKU\115-up\2020-12-01 20-06-56 result.json
上传成功的文件（0）：
上传失败的文件（1）：
KRMV-567.mp4
保存上传进度的文件（0）：

S:\DMM-H265\等待上传>
