### ISSUE TITLE
指定网络接口

### ISSUE THREAD

**Issue by lloyd18** [orzogc/fake115uploader#62]
由于本机到115的网络太烂，于是装了 warp 非全局，（全局的话影响其它网络）现在需要使用 WARP 网络接口来上传，希望可以指定

**Comment by lloyd18** [comment]
![image](https://github.com/orzogc/fake115uploader/assets/10294460/63c1d8c9-6752-4de6-a8ed-95f7af3382d1)

**Comment by lloyd18** [comment]
代理试过了，不到1M，很慢，放弃，全局试了，能到 3M/s

**Comment by feijiaa1** [comment]
warp 可以跑10-15m/s，但是持续时间不长，容易断流。考虑其他大厂，azure，aws，gcp之类的。

**Comment by lloyd18** [comment]
> warp 可以跑10-15m/s，但是持续时间不长，容易断流。考虑其他大厂，azure，aws，gcp之类的。

雀食，不是长久之计，大厂太贵了，用不起。
不知道还有没有其它方法，比如 套 cloudflare cdn ，不会弄。
