### ISSUE TITLE
遇到一个新问题，上传成功后multipartUploadFile报错

### ISSUE THREAD

**Issue by zxhpipi** [orzogc/fake115uploader#7]
2020/12/03 22:28:26 发现文件 KRMV-939.mp4 的上传曾经中断过，现在开始断点续传
2020/12/03 22:28:26 断点续传模式上传文件：KRMV-939.mp4
按q键停止上传并退出程序，断点续传模式会自动保存上传进度
2.75 GiB / 2.75 GiB [------------------------------------------------------------------------------------------] 100.00% 3.97 MiB p/s 11m50s 2020/12/03 22:40:19 断点续传模式上传 KRMV-939.mp4 出现错误：multipartUploadFile() error: 断点续传模式上传 KRMV-939.mp4 失败
之前用0.2版本没事，最近升级0.3版本遇到的
检查上传的文件实际已经上传成功

**Comment by orzogc** [comment]
115改了api，你用最新代码试试

**Comment by zxhpipi** [comment]
OK,使用新版本代码成功
2020/12/03 23:39:27 发现文件 KRMV-941.mp4 的上传曾经中断过，现在开始断点续传
2020/12/03 23:39:27 断点续传模式上传文件：KRMV-941.mp4
按q键停止上传并退出程序，断点续传模式会自动保存上传进度
3.40 GiB / 3.40 GiB [-------------------------------------------------------------------------------------------] 100.00% 7.34 MiB p/s 7m54s 2020/12/03 23:47:26 断点续传模式上传 KRMV-941.mp4 成功
2020/12/03 23:47:26 删除存档文件 E:\IKU\115-up\KRMV-941.mp4.json
2020/12/03 23:47:26 成功删除原文件 KRMV-941.mp4
