### ISSUE TITLE
无法验证cookies问题，请各位大佬帮忙，谢谢

### ISSUE THREAD

**Issue by shiyan1012** [orzogc/fake115uploader#72]
115昨天抽风过后，不知道为什么fake115uploader就很难通过 cookies验证，关闭代理、重启、重新手机扫码登录115网盘、F12获取cookies，重试上传总是提示：
2024/09/17 01:03:17 请确定网络是否畅通或者cookies是否设置好，每一次登陆网页端115都要重设一次cookies
panic: initialize() error: getUserKey() error: cannot parse JSON: cannot parse number: unexpected char: "<"; unparsed tail: "<!doctypehtml><html lang=\"zh-cn\"><meta c...2024438627e522d\",\"lang\":\"cn\"}</textarea>"

goroutine 1 [running]:
main.checkErr(...)
        C:/Users/38455/GolandProjects/fake115uploader/main.go:104
main.main()
        C:/Users/38455/GolandProjects/fake115uploader/main.go:565 +0x719

随后使用ALIST进行115网盘cookies的验证，提示failed get objs: failed to list objs: invalid character 'a' looking for beginning of value
请各位大佬看看什么原因，谢谢。

**Comment by orzogc** [comment]
是不是IP在国外？
https://github.com/orzogc/fake115uploader/issues/71

**Comment by shiyan1012** [comment]
刚试了下又可以了，啥都没动，IP是国内的
