### ISSUE TITLE
传输完毕后，提示断点续传模式上传失败。

### ISSUE THREAD

**Issue by leeonix** [orzogc/fake115uploader#74]
使用-m参数，断点续传模式，传输完毕后出错。
1.77 GiB / 1.77 GiB [---------------------] 100.00% 5.10 MiB p/s 5m56s
断点续传模式上传 mp4 出现错误：multipartUploadFile() error: 断点续传模式上传 mp4 失败
但使用-u参数就能上传成功。

**Comment by free-150** [comment]
今天一样出现这个问题

**Comment by orzogc** [comment]
OSS上传应该是成功的，就是不知道115那里改了什么

**Comment by free-150** [comment]
使用-u 也是很多文件会上传失败，多上传几次却可以成功

**Comment by leeonix** [comment]
> > OSS上传应该是成功的
> 
> 经常到不了OSS上传那一步就报错400了

这个写个脚本判断，重复常识就可以了，3、4次就成功了。

**Comment by lloyd18** [comment]
> 不知道是否是115那边又被攻击了调高防火墙设置还是怎么了 今天这边上传也是一堆出错 （用的是 -u） `普通模式上传 test 出现错误：ossUploadFile() error: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage="Authorization header is invalid.", RequestId=[REDACTED], Ec=[REDACTED]`

-m 也这样

**Comment by jerryandtom007** [comment]
> > 不知道是否是115那边又被攻击了调高防火墙设置还是怎么了 今天这边上传也是一堆出错 （用的是 -u） `普通模式上传 test 出现错误：ossUploadFile() error: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage="Authorization header is invalid.", RequestId=[REDACTED], Ec=[REDACTED]`
> 
> -m 也这样

-m是传到100%最后验证报错，-u开始就400，多重试几次还能用至少可以完成上传。

**Comment by lloyd18** [comment]
> > > 经常到不了OSS上传那一步就报错400了
> > 
> > 
> > 这个写个脚本判断，重复常识就可以了，3、4次就成功了。
> 
> 不用脚本，until do 就行。但是大文件每次都要重新计算sha1，费时而且伤硬盘 @orzogc 出错后能保存之前计算结果sha1吗？这样能避免反复重新计算。

我用 -m 根本上传不了，无论重试多少次

**Comment by 362227** [comment]
> https://github.com/cloud-fs/cloud-fs.github.io/releases/tag/v0.8.0-beta3
> 
> 看clouddrive那边，应该是被玩刮削的和上传文件加密的滥用废了。不知道将来如何了。 有人看过现在官方客户端上传会出错么？

客户端还算正常，大文件偶尔报错，重试几次就可以了

**Comment by 362227** [comment]
> 看到群里有人说 https://pypi.org/project/p115client/ 这个可以上传大体积文件了

能不能写个示例代码，我直接套用就可以了，换cookie、文件路径、目标目录（cid）就能用的那种

**Comment by 362227** [comment]
> > > 看到群里有人说 https://pypi.org/project/p115client/ 这个可以上传大体积文件了
> > 
> > 
> > 实测可以，大概情况是小于20GB可以，大于20GB会出问题
> 
> 超过20 GB出错是老问题了。 [#67 (comment)](https://github.com/orzogc/fake115uploader/issues/67#issuecomment-2054207184) 现在可能续传没法了？也不能分片了？

分片续传都可以，目前就是大于20GB的传不了

**Comment by 362227** [comment]
> 现在 -u 的上传成功率不超3成。测试了100个小体积的 Instagram reel 文件，100个就成功上传26个，就是不懂为什么115会随机返回400和200

客户端正常很多，这几天传了很多，超大文件也传了不少，出错继续就可以了，一般会出现几次错误，继续就可以了，不用重新开始。命令行工具上传大于20GB的成功率为0

**Comment by UVJkiNTQ** [comment]
看了alist那边的issue，上传的接口有改动

**Comment by jerryandtom007** [comment]
-u，是不是恢复了？今天中午和晚上（-u）上传一次400都没有，-m目前还不行100%后验证过不了。

**Comment by xwxbug** [comment]
今天看了下115浏览器,发现似乎只能用顺序的文件切片上传到OSS.
以前的不管顺序的一股脑将分片上传会在完成时返回
`
    "state":false,
    "message":"校验文件失败，请重新上传。",
    "code":10002
`
初始OSS请求 URI 里面有个sequential参数,有没有等号无所谓.

> https://fhnfile.oss-cn-*.com/ffffffffffffffffffffffffffffffffffffffffffffffffff?sequential=&uploads=

完成时,请求头中有个文件的SHA1.
x-oss-hash-sha1:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

希望对作者有帮助.
如果顺序上传,上传下一个切片需要上一个存在,这样多线程就毫无意义.只能线性的上传.

**Comment by power12317** [comment]
> 楼上发现得真仔细，我周末研究了一个通宵+一整个白天，到周日晚上才研究出来是这个问题，所以我自己把自己的本地版本改好了。 重点就是必须线性上传才能支持SHA1。

PS:我改造的伪单线程也不奏效，别的线性上传平台可以通过伪单线程方式来实现并发，但是oss只要上传1mb的chunk就立即拦截说顺序不对了。 原本多线程速度能跑满千兆，现在单线程只能2mb/s太难受了

**Comment by power12317** [comment]
> 可以分享吗？慢比没法上传好。

我本地的改版太多了，从早期改成多线程并发，到支持相对路径上传等等 乱七八糟的 ，毕竟go语言新手。还是等作者更新吧。
很简单就
bucket.InitiateMultipartUpload()下加个
oss.Sequential(),

然后
bucket.CompleteMultipartUpload()下加个
oss.SetHeader("x-oss-hash-sha1", ft.SHA1),
确保是单线程顺序上传，然后go build编译出来就行了

另外bucket.UploadPart() 是否要加MD5验证就不知道了，反正115浏览器是有的，我也做了一个MD5计算加了个
oss.ContentMD5(md5B64), 

本回复文一小时后删除

**Comment by 362227** [comment]
> 我本地的改版太多了，从早期改成多线程并发，到支持相对路径上传等等 乱七八糟的 ，毕竟go语言新手。还是等作者更新吧。 很简单就 bucket.InitiateMultipartUpload()下加个 oss.Sequential(),
> 
> 然后 bucket.CompleteMultipartUpload()下加个 oss.SetHeader("x-oss-hash-sha1", ft.SHA1), 确保是单线程顺序上传，然后go build编译出来就行了
> 
> 另外bucket.UploadPart() 是否要加MD5验证就不知道了，反正115浏览器是有的，我也做了一个MD5计算加了个 oss.ContentMD5(md5B64),

我海外上传-u可以达到20M/s，这种修改的方法是不是和-u是一样的了

**Comment by lloyd18** [comment]
> 可以用本项目https://github.com/wiserain/rclone 亲测20G的文件可以上传

不支持 115，你怎么用的

**Comment by SingleRottenChips** [comment]
> 可以用这个项目https://github.com/wiserain/rclone 亲测20G的文件可以上传

感谢🙇🏻‍♂️🙏🏻 
试了下上传图片，成功了；等过了晚高峰再试试看大文件。请问需要添加 --115-upload-cutoff参数吗？以及设为哪个值比较合适？

**Comment by lloyd18** [comment]
> > > 可以用本项目https://github.com/wiserain/rclone 亲测20G的文件可以上传
> > 
> > 
> > 不支持 115，你怎么用的
> > 编辑：原来是改版，我去试试 再编辑：上传不了，即便是小文件，可能是我不会用
> > ```
> > root@AT1:~# rclone move 20241029200150.mp4 115:/rclone --115-upload-cutoff -P
> > 2024/10/29 20:42:35 ERROR : 20241029200150.mp4: Failed to copy: failed to upload: multipart upload failed to finalize: API State false: 校验文件失败，请重新上传。 (10002)
> > ```
> 
> 文件大小没加

实际上我在 -115-upload-cutoff 后面填了 100000，复制的时候删除了

**Comment by 362227** [comment]
> 可以用这个项目https://github.com/wiserain/rclone 亲测20G的文件可以上传

测试了16GB的文件，不行，校验文件失败，请重新上传。 (10002)。
 -115-upload-cutoff 设置多大呢

**Comment by SingleRottenChips** [comment]
```
Option upload_cutoff.
Cutoff for switching to chunked upload.
Any files larger than this will be uploaded in chunks of chunk_size.
The minimum is 0 and the maximum is 5 GiB.
Enter a size with suffix K,M,G,T. Press Enter for the default (200Mi).
upload_cutoff> 
```

应该是最多只能设 5 GiB 吧？(我们为什么要在这里讨论另一个项目...）
