### ISSUE TITLE
关于代理的问题

### ISSUE THREAD

**Issue by free-150** [orzogc/fake115uploader#75]
我在阿里云一台服务器且可以在云服务器上走内网上传文件但是性能太差了，我在服务器上开了vpn server和http代理服务器。
用本主机连接vpn或使用`fake115uploader `时设置 export http(s)_proxy，无法走内网上传文件，不知道这样的想法行不不行。

**Comment by orzogc** [comment]
试试用`-oss-proxy`设置OSS代理为你的VPN

**Comment by free-150** [comment]
有用，但是上传还是受限于本地机器的最大上传，达不到内网效果
