### ISSUE TITLE
使用 -a 参数进行内网上传，提示本次运行没有上传文件

### ISSUE THREAD

**Issue by yuandx123** [orzogc/fake115uploader#78]
使用 -a 参数进行内网上传
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/48d191be-2746-4769-91eb-f55c82913346">
服务器地域
<img width="794" alt="image" src="https://github.com/user-attachments/assets/463f032b-a18e-4cfb-b667-2384bba17a65">
配置文件
<img width="1406" alt="image" src="https://github.com/user-attachments/assets/adafb8c5-3832-4741-b3e1-3b19e79fad90">

请问原因可能是什么呢？

**Comment by orzogc** [comment]
要上传的文件需要放在最后的位置
