### ISSUE TITLE
从昨天开始完全无法使用

### ISSUE THREAD

**Issue by huanongying27** [orzogc/fake115uploader#79]
目前只能使用秒传模式，m模式上个月出问题，改用u模式，目前m，u模式均出现以下错误形式

panic: initialize() error: 排序文件夹 xxxx 出现错误：[231 153 187 229 189 149 232 182 133 230 151 182 239 188 140 232 175 183 233 135 141 230 150 176 231 153 187 229 189 149 227 128 130]

goroutine 1 [running]:
main.checkErr(...)
        /home/orzogc/src/go/fake115uploader/main.go:104
main.main()
        /home/orzogc/src/go/fake115uploader/main.go:563 +0x6ec

**Comment by orzogc** [comment]
测试了一下，`-m`和`-u`上传都是正常的，需要编译最新的代码，或者你的115 cookies过期了

**Comment by huanongying27** [comment]
如何编译？这个小白真的不懂，我用的都是你们编译好的，如果115cookie有问题，f也就是秒传模式他会提示的，但是我这边f模式是可以的

**Comment by huanongying27** [comment]
> 测试了一下，`-m`并且`-u`都是上传正常的，需要编译最新的代码，或者你的115 cookies过期或者有问题

如何编译？这个小白真的不懂，我用的都是你们编译好的，如果115cookie有问题，f也就是秒传模式他会提示的，但是我这边f模式是可以的

**Comment by huanongying27** [comment]
大大，我重新扫码换了cookie还是没用，我用秒传模式也就是-f模式是没问题的

**Comment by orzogc** [comment]
请下载使用最新版本
https://github.com/orzogc/fake115uploader/releases/tag/v0.6.2

**Comment by huanongying27** [comment]
> 请下载使用最新版本 https://github.com/orzogc/fake115uploader/releases/tag/v0.6.2

谢谢，但是我试了下还是这样子😭

**Comment by orzogc** [comment]
你IP是不是在国外？

**Comment by huanongying27** [comment]
> 你IP是不是在国外？

不是啊，而且你的设置强制默认不走代理的

**Comment by huanongying27** [comment]
会不会是115对我的账号进行风控了啊，目前只能f-

**Comment by orzogc** [comment]
这个就不清楚了，可能你的帐号被115官方限制了

**Comment by huanongying27** [comment]
panic: initialize() error: 排序文件夹 xxxx 出现错误：[231 153 187 229 189 149 232 182 133 230 151 182 239 188 140 232 175 183 233 135 141 230 150 176 231 153 187 229 189 149 227 128 130]

goroutine 1 [running]:
main.checkErr(...)
/home/orzogc/src/go/fake115uploader/main.go:104
main.main()
/home/orzogc/src/go/fake115uploader/main.go:563 +0x6ec

反正错误是这样显示，我看不懂😭

**Comment by huanongying27** [comment]
但是不对啊，m-u模式都会先进行秒传的，这个第一个步骤三个都一样的，问题是mu模式直接就这样

**Comment by orzogc** [comment]
> [231 153 187 229 189 149 232 182 133 230 151 182 239 188 140 232 175 183 233 135 141 230 150 176 231 153 187 229 189 149 227 128 130]

这段的意思就是`登录超时，请重新登录。`
你帐号没登陆或者cookies有问题

**Comment by huanongying27** [comment]
> > [231 153 187 229 189 149 232 182 133 230 151 182 239 188 140 232 175 183 233 135 141 230 150 176 231 153 187 229 189 149 227 128 130]
> 
> 这段的意思就是`登录超时，请重新登录。` 你帐号没登陆或者cookies有问题

但是我用f模式他会直接进行秒传也就是mu模式的第一步骤，并不会出现这样的错误

**Comment by huanongying27** [comment]
如果文件有，也确实能成功

**Comment by orzogc** [comment]
> > > [231 153 187 229 189 149 232 182 133 230 151 182 239 188 140 232 175 183 233 135 141 230 150 176 231 153 187 229 189 149 227 128 130]
> > 
> > 
> > 这段的意思就是`登录超时，请重新登录。` 你帐号没登陆或者cookies有问题
> 
> 但是我用f模式他会直接进行秒传也就是mu模式的第一步骤，并不会出现这样的错误

因为-f不会排序文件夹，其他的会

**Comment by orzogc** [comment]
你指定上传的115里的文件夹没问题吧？

**Comment by huanongying27** [comment]
> 排序文件夹

排序文件夹是

> 你指定上传的115里的文件夹没问题吧？ 文件夹里的文件数量是有限制的

排序文件夹是啥意思？文件夹没问题，之前一直都是那个，后面我改成0还是这样，你的意思是说我建立了太多文件夹吗？

**Comment by huanongying27** [comment]
> 你指定上传的115里的文件夹没问题吧？ 文件夹里的文件数量是有限制的

里面的文件才233个而已

**Comment by orzogc** [comment]
要么你帐号被限制了，要么帐号cookies有问题，估计就这两种情况

**Comment by huanongying27** [comment]
> 要么你帐号被限制了，要么帐号cookies有问题，估计就这两种情况

cookie有问题不是这种错误的吧，而且f模式都好好的，如果账号限制该怎么办啊

**Comment by orzogc** [comment]
注册个新帐号，用新帐号上传试试

**Comment by huanongying27** [comment]
无语了，现在连秒传模式也用不了了，一直显示cookies错误，问题是我都是按照以前的格式操作的，也是重新获取的，这咋搞，始终不知道问题在哪里，想放弃了用那破浏览器算了

**Comment by orzogc** [comment]
> 新版本加了个kid参数

哪里的参数？

**Comment by huanongying27** [comment]
> > > 新版本加了个kid参数
> > 
> > 
> > 哪里的参数？
> 
> cookie上的 除了uid, cid, seid 多了一个kid（新获取的cookie有） 参考[AlistGo/alist#7626](https://github.com/AlistGo/alist/pull/7626)

大佬，请问怎么获取到最新版本的cookie值呢，我用脚本跟插件还是只有原来那三个

**Comment by huanongying27** [comment]
> > > 新版本加了个kid参数
> > 
> > 
> > 哪里的参数？
> 
> cookie上的 除了uid, cid, seid 多了一个kid（新获取的cookie有） 参考[AlistGo/alist#7626](https://github.com/AlistGo/alist/pull/7626)
我在插件里看到了，脚本没显示

**Comment by huanongying27** [comment]
> 新版本加了个kid参数

大佬，真的太感谢了，不仅秒传模式能用，m跟u也能用了
